import * as path from "path";
import * as crypto from "crypto";
import type { Role, Feature, LicenseCodeRecord } from "@karate/core";
import { readJsonSafe, writeJson } from "./storage";

/**
 * License storage layout (file-based JSON, single file).
 *
 * codes: claim-code records. A code is generated by a superadmin and emailed
 *   out-of-band. It is the user's only entry point to the system.
 * licenses: live and historical JWT lineages. Each `jti` issued by /api/renew
 *   creates a new entry in `lineages[codeId]`, but they share `userId`, role,
 *   features, and `activatedAt` with the original code.
 *
 * A "lineage" is the chain of all JWTs ever issued for one redeemed claim
 * code. Revoking a lineage rejects all future renewals on every machine.
 */

export interface ClaimCodeRecord {
  /** Stable id; SHA-256(code) so the raw 6-digit value is never persisted. */
  codeId: string;
  /** Raw 6-digit code, kept in memory only for the lifetime of the response
   *  that created it. Set to null on persistence so the file never contains it. */
  rawCodeMemoryOnly: string | null;
  /** Stable opaque userId — the JWT `sub` claim. */
  userId: string;
  label: string;
  role: Role;
  features: Feature[];
  plan: string;
  createdAt: number;
  expiresAt: number;
  /** Once redeemed, this is the wall-clock timestamp of activation. */
  activatedAt: number | null;
  /** Machine fingerprint registered at activation time. */
  machineFingerprint: string | null;
  /** Whether the code is single-use-consumed. */
  used: boolean;
  /** Set by `transferLicense` to allow re-redemption on a fresh machine. */
  reclaimable: boolean;
  /** Latest JWT id issued in this lineage. */
  currentJti: string | null;
  /** Whether the entire lineage is revoked (every renewal will be rejected). */
  revoked: boolean;
  lastRenewalAt: number | null;
}

interface LicensesFile {
  version: number;
  /** SHA-256(code) → record. The raw code only exists in the response that
   *  creates it; only its hash is ever written to disk. */
  codes: Record<string, ClaimCodeRecord>;
  /** Tombstoned JWTs (jti) — used for fast revocation lookup. */
  revokedJtis: string[];
}

const FILE_VERSION = 1;
const FILE_NAME = "licenses.json";

function filePath(dataDir: string): string {
  return path.join(dataDir, FILE_NAME);
}

function hashCode(code: string): string {
  return crypto.createHash("sha256").update(code).digest("hex");
}

function generate6DigitCode(): string {
  // crypto-strong unbiased 0..999999
  while (true) {
    const buf = crypto.randomBytes(4);
    const n = buf.readUInt32BE(0);
    // Use rejection sampling to avoid modulo bias
    const max = Math.floor(0xffffffff / 1_000_000) * 1_000_000;
    if (n < max) return String(n % 1_000_000).padStart(6, "0");
  }
}

export class LicenseStore {
  private file: LicensesFile;
  constructor(private dataDir: string) {
    this.file = readJsonSafe<LicensesFile>(filePath(dataDir), {
      version: FILE_VERSION,
      codes: {},
      revokedJtis: [],
    });
    if (!this.file.codes) this.file.codes = {};
    if (!this.file.revokedJtis) this.file.revokedJtis = [];
  }

  private persist(): void {
    writeJson(filePath(this.dataDir), this.file);
  }

  /** Create a new unused claim code. Returns the raw 6-digit value so the
   *  superadmin can display it once. Subsequent reads return only metadata. */
  createCode(opts: {
    role: Role;
    features: Feature[];
    plan?: string;
    label: string;
    ttlMs?: number;
  }): { code: string; record: ClaimCodeRecord } {
    const code = generate6DigitCode();
    const codeId = hashCode(code);
    if (this.file.codes[codeId]) {
      // Astronomically unlikely collision — recurse.
      return this.createCode(opts);
    }
    const now = Date.now();
    const ttl = opts.ttlMs ?? 30 * 24 * 60 * 60 * 1000;
    const record: ClaimCodeRecord = {
      codeId,
      rawCodeMemoryOnly: code,
      userId: "u_" + crypto.randomUUID(),
      label: opts.label,
      role: opts.role,
      features: opts.features,
      plan: opts.plan ?? opts.role,
      createdAt: now,
      expiresAt: now + ttl,
      activatedAt: null,
      machineFingerprint: null,
      used: false,
      reclaimable: false,
      currentJti: null,
      revoked: false,
      lastRenewalAt: null,
    };
    this.file.codes[codeId] = record;
    this.persist();
    return { code, record };
  }

  /** Seed a code with a known value (test fixtures only). */
  seedCode(rawCode: string, opts: {
    role: Role;
    features: Feature[];
    plan?: string;
    label: string;
    ttlMs?: number;
  }): ClaimCodeRecord | null {
    const codeId = hashCode(rawCode);
    if (this.file.codes[codeId]) return null;
    const now = Date.now();
    const ttl = opts.ttlMs ?? 30 * 24 * 60 * 60 * 1000;
    const record: ClaimCodeRecord = {
      codeId,
      rawCodeMemoryOnly: null,
      userId: "u_" + crypto.randomUUID(),
      label: opts.label,
      role: opts.role,
      features: opts.features,
      plan: opts.plan ?? opts.role,
      createdAt: now,
      expiresAt: now + ttl,
      activatedAt: null,
      machineFingerprint: null,
      used: false,
      reclaimable: false,
      currentJti: null,
      revoked: false,
      lastRenewalAt: null,
    };
    this.file.codes[codeId] = record;
    this.persist();
    return record;
  }

  findByCode(rawCode: string): ClaimCodeRecord | null {
    return this.file.codes[hashCode(rawCode)] ?? null;
  }

  findByJti(jti: string): ClaimCodeRecord | null {
    for (const r of Object.values(this.file.codes)) {
      if (r.currentJti === jti) return r;
    }
    return null;
  }

  findByUserId(userId: string): ClaimCodeRecord | null {
    for (const r of Object.values(this.file.codes)) {
      if (r.userId === userId) return r;
    }
    return null;
  }

  /** Returns true if a different unrevoked, used lineage already owns this
   *  machine fingerprint. */
  isMachineRegisteredElsewhere(machineFingerprint: string, exceptCodeId?: string): boolean {
    for (const r of Object.values(this.file.codes)) {
      if (r.codeId === exceptCodeId) continue;
      if (r.revoked) continue;
      if (!r.used) continue;
      if (r.machineFingerprint === machineFingerprint) return true;
    }
    return false;
  }

  /** Mark a code redeemed (single-use). Subsequent activations of the same
   *  raw code with a different fingerprint will be rejected unless the
   *  superadmin sets `reclaimable`. */
  activate(codeId: string, machineFingerprint: string, jti: string): void {
    const r = this.file.codes[codeId];
    if (!r) return;
    const now = Date.now();
    r.used = true;
    r.reclaimable = false;
    r.activatedAt = r.activatedAt ?? now;
    r.machineFingerprint = machineFingerprint;
    r.currentJti = jti;
    r.lastRenewalAt = now;
    this.persist();
  }

  /** Rotate the lineage's current jti on renewal. */
  rotateJti(codeId: string, newJti: string): void {
    const r = this.file.codes[codeId];
    if (!r) return;
    if (r.currentJti) this.file.revokedJtis.push(r.currentJti);
    r.currentJti = newJti;
    r.lastRenewalAt = Date.now();
    this.persist();
  }

  /** Revoke an entire lineage. All future renewals will be rejected. */
  revokeLineage(codeId: string): boolean {
    const r = this.file.codes[codeId];
    if (!r) return false;
    r.revoked = true;
    if (r.currentJti) this.file.revokedJtis.push(r.currentJti);
    r.currentJti = null;
    this.persist();
    return true;
  }

  /** Revoke just one jti (e.g. for the current device) while keeping the
   *  lineage alive so the user can renew again on a fresh activation. */
  revokeJti(jti: string): void {
    if (!this.file.revokedJtis.includes(jti)) {
      this.file.revokedJtis.push(jti);
      this.persist();
    }
  }

  isRevoked(jti: string): boolean {
    return this.file.revokedJtis.includes(jti);
  }

  /** Reset the machine fingerprint so the holder of the original code can
   *  activate on a fresh machine. */
  transfer(codeId: string): boolean {
    const r = this.file.codes[codeId];
    if (!r) return false;
    if (r.currentJti) this.file.revokedJtis.push(r.currentJti);
    r.used = false;
    r.reclaimable = true;
    r.machineFingerprint = null;
    r.currentJti = null;
    this.persist();
    return true;
  }

  /** Extend the claim-code expiry. No effect if already redeemed. */
  extendExpiry(codeId: string, newExpiresAt: number): boolean {
    const r = this.file.codes[codeId];
    if (!r) return false;
    if (r.used) return false;
    r.expiresAt = newExpiresAt;
    this.persist();
    return true;
  }

  /** Public read of all codes for the admin panel. The raw code is only
   *  available on initial creation (`createCode`) — listing here returns
   *  preview/metadata only. */
  list(): LicenseCodeRecord[] {
    const now = Date.now();
    return Object.values(this.file.codes)
      .filter((r) => !r.revoked && r.expiresAt >= now)
      .map((r) => {
      const status: LicenseCodeRecord["status"] = r.used ? "active" : "unused";
      return {
        code: r.rawCodeMemoryOnly ?? "",
        codePreview: r.rawCodeMemoryOnly ? r.rawCodeMemoryOnly : "**" + r.codeId.slice(0, 2),
        userId: r.userId,
        role: r.role,
        features: r.features,
        label: r.label,
        createdAt: r.createdAt,
        expiresAt: r.expiresAt,
        status,
        machineFingerprintTail: r.machineFingerprint
          ? r.machineFingerprint.slice(-8)
          : null,
        activatedAt: r.activatedAt,
        jti: r.currentJti,
        lastRenewalAt: r.lastRenewalAt,
      };
    });
  }

  /** Look up by userId (used in admin transfer/revoke endpoints). */
  findCodeIdByUserId(userId: string): string | null {
    for (const [codeId, r] of Object.entries(this.file.codes)) {
      if (r.userId === userId) return codeId;
    }
    return null;
  }
}
